// C-NAPSE 2026 카드 데이터
// 이미지는 GitHub raw URL로 로드

const GH_BASE = "https://raw.githubusercontent.com/JonathanBlackDoctor/cmf-synapse-2026/main/";
const IMG = {
  "01_rod.png": "1.%20간상세포.png",
  "02_cone.png": "2.%20원추세포.png",
  "03_retinal_bipolar.png": "3.%20망막%20양극세포.png",
  "04_horizontal.png": "4.%20수평세포.png",
  "05_amacrine.png": "5.%20무축삭세포.png",
  "06_retinal_ganglion.png": "6.%20망막%20신경절세포.png",
  "07_olfactory_receptor.png": "7.%20후각수용뉴런.png",
  "08_mitral.png": "8.%20승모세포.png",
  "09_tufted.png": "9.%20솔방울세포%20.png",
  "10_olfactory_granule.png": "10.%20후각구%20과립세포.png",
  "11_inner_hair.png": "11.%20내유모세포.png",
  "12_outer_hair.png": "12.%20외유모세포.png",
  "13_merkel.png": "13.%20메르켈세포.png",
  "14_pacinian.png": "14.%20파치니소체%20구심뉴런.png",
  "15_meissner.png": "15.%20마이스너소체%20구심뉴런.png",
  "16_ruffini.png": "16.%20루피니종말%20구심뉴런.png",
  "17_muscle_spindle.png": "17.%20근방추%20Ia%20구심뉴런.png",
  "18_golgi_tendon.png": "18.%20골지건기관%20Ib%20구심뉴런.png",
  "19_free_nerve.png": "19.%20자유신경종말.png",
  "20_drg.png": "20.%20후근신경절%20의사단극세포.png",
  "21_purkinje.png": "21.%20푸르키네%20세포.png",
  "22_cerebellar_granule.png": "22.%20소뇌%20과립세포.png",
  "23_climbing_fiber.png": "23.%20등반섬유%20뉴런.png",
  "24_mossy_fiber.png": "24.%20이끼섬유%20뉴런.png",
  "25_cerebellar_basket.png": "25.%20소뇌%20바구니세포.png",
  "26_cerebellar_stellate.png": "26.%20소뇌%20별세포.png",
  "27_golgi_cell.png": "27.%20골지%20세포.png",
  "28_lugaro.png": "28.%20루가로%20세포.png",
  "29_unipolar_brush.png": "29.%20단극솔세포.png",
  "30_pyramidal.png": "30.%20피라미드%20세포.png",
  "31_betz.png": "31.%20베츠%20세포.png",
  "32_von_economo.png": "32.%20방추상%20뉴런%20%20폰%20에코노모%20뉴런.png",
  "33_chandelier.png": "33.%20샹들리에%20세포.png",
  "34_cortical_basket.png": "34.%20피질%20바구니세포.png",
  "35_double_bouquet.png": "35.%20더블부케%20세포.png",
  "36_martinotti.png": "36.%20마르티노티%20세포.png",
  "37_cajal_retzius.png": "37.%20카할-레치우스%20세포.png",
  "38_cortical_stellate.png": "38.%20피질%20성상세포.png",
  "39_neurogliaform.png": "39.%20뉴로글리아폼%20세포.png",
  "40_dentate_granule.png": "40.%20치아이랑%20과립세포.png",
  "41_ca1_pyramidal.png": "41.%20CA1%20피라미드%20세포.png",
  "42_ca3_pyramidal.png": "42.%20CA3%20피라미드%20세포.png",
  "43_mossy_cell.png": "43.%20해마%20이끼세포.png",
  "44_olm.png": "44.%20O-LM%20세포.png",
  "45_medium_spiny.png": "45.%20중간가시뉴런.png",
  "46_cholinergic.png": "46.%20선조체%20콜린성%20중간뉴런.png",
  "47_dopaminergic.png": "47.%20도파민%20뉴런.png",
  "48_locus_coeruleus.png": "48.%20청반핵%20뉴런.png",
  "49_raphe.png": "49.%20솔기핵%20뉴런.png",
  "50_thalamic_relay.png": "50.%20시상%20중계뉴런.png",
  "51_thalamic_reticular.png": "51.%20시상%20망상핵%20뉴런.png",
  "52_magnocellular.png": "52.%20거대세포%20신경분비뉴런.png",
  "53_alpha_motor.png": "53.%20알파%20운동뉴런.png",
  "54_gamma_motor.png": "54.%20감마%20운동뉴런.png",
  "55_renshaw.png": "55.%20렌쇼%20세포.png",
  "56_mauthner.png": "56.%20마우트너%20세포.png",
  "57_sympathetic.png": "57.%20교감신경절%20뉴런.png",
  "58_parasympathetic.png": "58.%20부교감신경절%20뉴런.png",
  "59_dogiel_i.png": "59.%20도기엘%20I형%20세포.png",
  "60_dogiel_ii.png": "60.%20도기엘%20II형%20세포.png",
};
const imgUrl = (name) => GH_BASE + (IMG[name] || name);

// 성경 구절 (그룹별 배정)
const VERSES = {
  "G.01": { text: '그에게서 온 몸이 각 마디를 통하여 도움을 받음으로 연결되고 결합되어 각 지체의 분량대로 역사하여 그 몸을 자라게 하며 <span style="white-space:nowrap;">사랑 안에서 스스로 세우느니라</span>', ref_en: "Ephesians", ref_ko: "에베소서 4:16" },
  "G.02": { text: '너희는 그리스도의 몸이요 <span style="white-space:nowrap;">지체의 각 부분이라</span>', ref_en: "1 Corinthians", ref_ko: "고린도전서 12:27" },
  "G.03": { text: '철이 철을 날카롭게 하는 것 같이 사람이 그의 친구의 <span style="white-space:nowrap;">얼굴을 빛나게 하느니라</span>', ref_en: "Proverbs", ref_ko: "잠언 27:17" },
  "G.04": { text: '마음을 같이하여 같은 사랑을 가지고 <span style="white-space:nowrap;">뜻을 합하며 한마음을 품어</span>', ref_en: "Philippians", ref_ko: "빌립보서 2:2" },
  "G.05": { text: '보라 형제가 연합하여 동거함이 어찌 그리 <span style="white-space:nowrap;">선하고 아름다운고</span>', ref_en: "Psalm", ref_ko: "시편 133:1" },
  "G.06": { text: '이와 같이 우리 많은 사람이 그리스도 안에서 한 몸이 되어 <span style="white-space:nowrap;">서로 지체가 되었느니라</span>', ref_en: "Romans", ref_ko: "로마서 12:5" },
  "G.07": { text: '머리를 붙들지 아니하는지라 온 몸이 머리로 말미암아 마디와 힘줄로 공급함을 받고 연합하여 <span style="white-space:nowrap;">하나님이 자라게 하시므로 자라느니라</span>', ref_en: "Colossians", ref_ko: "골로새서 2:19" },
  "G.08": { text: '마지막으로 말하노니 너희가 다 마음을 같이하여 동정하며 형제를 사랑하며 <span style="white-space:nowrap;">불쌍히 여기며 겸손하며</span>', ref_en: "1 Peter", ref_ko: "베드로전서 3:8" },
  "G.09": { text: '사랑하는 자들아 하나님이 이같이 우리를 사랑하셨은즉 <span style="white-space:nowrap;">우리도 서로 사랑하는 것이 마땅하도다</span>', ref_en: "1 John", ref_ko: "요한일서 4:11" },
  "G.10": { text: '평안의 매는 줄로 성령이 <span style="white-space:nowrap;">하나 되게 하신 것을 힘써 지키라</span>', ref_en: "Ephesians", ref_ko: "에베소서 4:3" },
  "G.11": { text: '이 모든 것 위에 사랑을 더하라 <span style="white-space:nowrap;">이는 온전하게 매는 띠니라</span>', ref_en: "Colossians", ref_ko: "골로새서 3:14" },
};
VERSES["G.12"] = VERSES["G.01"];
VERSES["G.13"] = VERSES["G.03"];
VERSES["G.14"] = VERSES["G.05"];
VERSES["G.15"] = VERSES["G.02"];
VERSES["G.16"] = VERSES["G.06"];
VERSES["G.17"] = VERSES["G.09"];

// 선배(17명)
const SENIORS = [
  { group: "G.01", name: "김예은", info: "간4", neuron_name: "Horizontal Cell",            image: "04_horizontal.png",         soma_y: 0.50, juniors_idx: [0,1,2] },
  { group: "G.02", name: "이은수", info: "간3", neuron_name: "Olfactory Receptor Neuron",  image: "07_olfactory_receptor.png", soma_y: 0.50, juniors_idx: [3,4,39] },
  { group: "G.03", name: "이근우", info: "간2", neuron_name: "Golgi Cell",                 image: "27_golgi_cell.png",         soma_y: 0.45, noClamp: true, juniors_idx: [5,6,7,8] },
  { group: "G.04", name: "변은성", info: "간2", neuron_name: "Climbing Fiber",             image: "23_climbing_fiber.png",     soma_y: 0.30, juniors_idx: [9,10,11] },
  { group: "G.05", name: "박동빈", info: "본4", neuron_name: "Cortical Spiny Stellate",    image: "38_cortical_stellate.png",  soma_y: 0.52, juniors_idx: [12,13] },
  { group: "G.06", name: "김지현", info: "본4", neuron_name: "Purkinje Cell",              image: "21_purkinje.png",           soma_y: 0.60, juniors_idx: [14] },
  { group: "G.07", name: "채성준", info: "본3", neuron_name: "Cerebellar Basket Cell",     image: "25_cerebellar_basket.png",  soma_y: 0.35, juniors_idx: [15,16,17] },
  { group: "G.08", name: "안수민", info: "본2", neuron_name: "Cerebellar Stellate Cell",   image: "26_cerebellar_stellate.png",soma_y: 0.50, juniors_idx: [18,19,20] },
  { group: "G.09", name: "정욱",   info: "본1", neuron_name: "O-LM Cell",                  image: "44_olm.png",                soma_y: 0.70, juniors_idx: [21,22] },
  { group: "G.10", name: "조나단", info: "본1", neuron_name: "Unipolar Brush Cell",        image: "29_unipolar_brush.png",     soma_y: 0.50, juniors_idx: [23,24] },
  { group: "G.11", name: "이채윤", info: "본1", neuron_name: "Lugaro Cell",                image: "28_lugaro.png",             soma_y: 0.50, juniors_idx: [25,26] },
  { group: "G.12", name: "이예진", info: "본1", neuron_name: "Mossy Fiber",                image: "24_mossy_fiber.png",        soma_y: 0.30, juniors_idx: [27,28] },
  { group: "G.13", name: "이승은", info: "본1", neuron_name: "Cerebellar Granule Cell",    image: "22_cerebellar_granule.png", soma_y: 0.50, juniors_idx: [29,30] },
  { group: "G.14", name: "이지현", info: "본1", neuron_name: "Amacrine Cell",              image: "05_amacrine.png",           soma_y: 0.35, juniors_idx: [31,32] },
  { group: "G.15", name: "안병욱", info: "예2", neuron_name: "Mauthner Cell",              image: "56_mauthner.png",           soma_y: 0.40, juniors_idx: [33,34] },
  { group: "G.16", name: "이민준", info: "예2", neuron_name: "Inner Hair Cell",            image: "11_inner_hair.png",         soma_y: 0.55, juniors_idx: [35,36] },
  { group: "G.17", name: "배주현", info: "예2", neuron_name: "Dogiel Type II Cell",        image: "60_dogiel_ii.png",          soma_y: 0.50, juniors_idx: [37,38] },
];

// 후배(39명)
const JUNIORS = [
  { group: "G.01", name: "김유진", neuron_name: "Rod Cell",                          image: "01_rod.png",              soma_y: 0.55 },
  { group: "G.01", name: "손지모", neuron_name: "Cone Cell",                         image: "02_cone.png",             soma_y: 0.55 },
  { group: "G.01", name: "안혜솔", neuron_name: "Retinal Ganglion Cell",             image: "06_retinal_ganglion.png", soma_y: 0.55 },
  { group: "G.02", name: "주현우", neuron_name: "Mitral Cell",                       image: "08_mitral.png",           soma_y: 0.50 },
  { group: "G.02", name: "김채윤", neuron_name: "Tufted Cell",                       image: "09_tufted.png",           soma_y: 0.50 },
  { group: "G.03", name: "김민서", neuron_name: "Merkel Cell",                       image: "13_merkel.png",           soma_y: 0.50 },
  { group: "G.03", name: "박규은", neuron_name: "Pacinian Corpuscle Afferent",       image: "14_pacinian.png",         soma_y: 0.30 },
  { group: "G.03", name: "신예원", neuron_name: "Meissner Corpuscle Afferent",       image: "15_meissner.png",         soma_y: 0.30 },
  { group: "G.03", name: "서지나", neuron_name: "Ruffini Ending Afferent",           image: "16_ruffini.png",          soma_y: 0.30 },
  { group: "G.04", name: "김예경", neuron_name: "Muscle Spindle Ia Afferent",        image: "17_muscle_spindle.png",   soma_y: 0.50 },
  { group: "G.04", name: "이연수", neuron_name: "Golgi Tendon Ib Afferent",          image: "18_golgi_tendon.png",     soma_y: 0.50 },
  { group: "G.04", name: "장현영", neuron_name: "Free Nerve Ending",                 image: "19_free_nerve.png",       soma_y: 0.50 },
  { group: "G.05", name: "강민서", neuron_name: "Pyramidal Cell",                    image: "30_pyramidal.png",        soma_y: 0.58 },
  { group: "G.05", name: "최은수", neuron_name: "Betz Cell",                         image: "31_betz.png",             soma_y: 0.58 },
  { group: "G.06", name: "노시현", neuron_name: "Von Economo Neuron",                image: "32_von_economo.png",      soma_y: 0.50 },
  { group: "G.07", name: "백도영", neuron_name: "Chandelier Cell",                   image: "33_chandelier.png",       soma_y: 0.42 },
  { group: "G.07", name: "박동위", neuron_name: "Cortical Basket Cell",              image: "34_cortical_basket.png",  soma_y: 0.48 },
  { group: "G.07", name: "박한주", neuron_name: "Double Bouquet Cell",               image: "35_double_bouquet.png",   soma_y: 0.50 },
  { group: "G.08", name: "오준혁", neuron_name: "Martinotti Cell",                   image: "36_martinotti.png",       soma_y: 0.50 },
  { group: "G.08", name: "박우진", neuron_name: "Cajal-Retzius Cell",                image: "37_cajal_retzius.png",    soma_y: 0.50 },
  { group: "G.08", name: "변선우", neuron_name: "Neurogliaform Cell",                image: "39_neurogliaform.png",    soma_y: 0.50 },
  { group: "G.09", name: "유창현", neuron_name: "CA1 Pyramidal Cell",                image: "41_ca1_pyramidal.png",    soma_y: 0.58 },
  { group: "G.09", name: "허민",   neuron_name: "CA3 Pyramidal Cell",                image: "42_ca3_pyramidal.png",    soma_y: 0.58 },
  { group: "G.10", name: "민진우", neuron_name: "Dentate Granule Cell",              image: "40_dentate_granule.png",  soma_y: 0.65 },
  { group: "G.10", name: "김민결", neuron_name: "Hippocampal Mossy Cell",            image: "43_mossy_cell.png",       soma_y: 0.50 },
  { group: "G.11", name: "윤홍현", neuron_name: "Medium Spiny Neuron",               image: "45_medium_spiny.png",     soma_y: 0.50 },
  { group: "G.11", name: "전소윤", neuron_name: "Striatal Cholinergic Interneuron",  image: "46_cholinergic.png",      soma_y: 0.50 },
  { group: "G.12", name: "정은아", neuron_name: "Dopaminergic Neuron",               image: "47_dopaminergic.png",     soma_y: 0.50 },
  { group: "G.12", name: "김민결", neuron_name: "Locus Coeruleus Neuron",            image: "48_locus_coeruleus.png",  soma_y: 0.45 },
  { group: "G.13", name: "고은별", neuron_name: "Raphe Nucleus Neuron",              image: "49_raphe.png",            soma_y: 0.45 },
  { group: "G.13", name: "강예은", neuron_name: "Thalamocortical Relay Neuron",      image: "50_thalamic_relay.png",   soma_y: 0.50 },
  { group: "G.14", name: "김도연", neuron_name: "Thalamic Reticular Neuron",         image: "51_thalamic_reticular.png", soma_y: 0.50 },
  { group: "G.14", name: "김수한", neuron_name: "Magnocellular Neurosecretory Neuron", image: "52_magnocellular.png",  soma_y: 0.42 },
  { group: "G.15", name: "이은수", neuron_name: "Alpha Motor Neuron",                image: "53_alpha_motor.png",      soma_y: 0.50 },
  { group: "G.15", name: "이상용", neuron_name: "Gamma Motor Neuron",                image: "54_gamma_motor.png",      soma_y: 0.50 },
  { group: "G.16", name: "조현호", neuron_name: "Renshaw Cell",                      image: "55_renshaw.png",          soma_y: 0.50 },
  { group: "G.16", name: "신원규", neuron_name: "DRG Pseudounipolar Neuron",         image: "20_drg.png",              soma_y: 0.50 },
  { group: "G.17", name: "이주하", neuron_name: "Sympathetic Ganglion Neuron",       image: "57_sympathetic.png",      soma_y: 0.52 },
  { group: "G.17", name: "손보경", neuron_name: "Parasympathetic Ganglion Neuron",   image: "58_parasympathetic.png",  soma_y: 0.52 },
  { group: "G.02", name: "권예준", neuron_name: "Olfactory Granule Cell",            image: "10_olfactory_granule.png", soma_y: 0.50 },
];

window.__CNAPSE = { imgUrl, VERSES, SENIORS, JUNIORS, IMG, GH_BASE };
